# Project information
site_name: Crystal Reports Schulungsunterlagen
site_description: 'Crystal Reports  Schulungsunterlagen'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.crystal-schulungen.stueber.de'

# Copyright
copyright:
  '&copy; 2023 STÜBER SYSTEMS GmbH : <a href="https://legal.stueber.de/imprint.php">Impressum</a> : <a href="https://legal.stueber.de/privacy.php">Datenschutz</a>'

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.crystal-schulungen.de'
    name: material
    language: de
    static_templates:
        - 404.html
    include_search_page: false
    search_index_only: true
    language: de
    features:
        - navigation.footer
        - navigation.instant
        - navigation.top
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'

# Customization
extra_css:
    - assets/css/custom.css

# Plugins    
plugins:
    - search
    - minify:
        minify_html: true
    
# Extensions    
markdown_extensions:
  - fancyboxmd
  - markdown.extensions.admonition
  - markdown.extensions.abbr
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde  
  
# Navigation  
nav:
- Überblick: index.md
- Schulungsvoraussetzungen: voraussetzungen.md
- Crystal Reports:
    - Grundlagen: basics.md
    - Formeln: formulas.md
    - Laufende Summenfelder: running_totals.md
    #- Gruppieren: groups.md
    #- Unterberichte: subreports.md
- Schritt-für-Schritt:
    - Überblick: step-by-step/overview.md
    - Einen bestehenden Bericht ändern: step-by-step/change_report.md
    - Eine Klassenliste von Grund auf neu erstellen: step-by-step/create_class_list.md
- Schulung:
    - Präsentation: presentation.md
