# Project information
site_name: Crystal Reports Schulungsunterlagen
site_description: 'Crystal Reports  Schulungsunterlagen'
site_author: 'STÜBER SYSTEMS GmbH'
site_url: 'https://doc.crystal-schulungen.stueber.de'

# Copyright
copyright: © 2022 STÜBER SYSTEMS GmbH

# Repository
repo_name: 'Auf GitHub'
repo_url: 'https://github.com/stuebersystems/doc.crystal-schulungen.de'

# Theming
theme: 
    name: material
    custom_dir: overrides
    language: de
    features:
        - instant
    palette:
        primary: 'blue'
        accent: 'deep orange'
    font: false
    favicon: assets/logos/favicon.ico
    logo: 'assets/logos/logo.svg'
    include_search_page: false
    search_index_only: true
    static_templates:
      - 404.html

# Legal links
extra:
  legal:
    - label: Impressum
      link: https://www.stueber.de/imprint.php
    - label: Datenschutz
      link: https://legal.stueber.de/privacy.php

# Customization
extra_css:
    - assets/css/custom.css
    
# Extensions    
markdown_extensions:
    - admonition
    - fancyboxmd

# Plugins    
plugins:
    - search
    #- img2fig    
  
# Navigation  
nav:
- Überblick: index.md
- Crystal Reports:
    - Grundlagen: basics.md
    - Formeln: formulas.md
    - Laufende Summenfelder: running_totals.md
    #- Gruppieren: groups.md
    #- Unterberichte: subreports.md
- Schrit-für-Schritt:
    - Überblick: step-by-step/overview.md
    - Einen bestehenden Bericht ändern: step-by-step/change_report.md
    - Eine Klassenliste von Grund auf neu erstellen: step-by-step/create_class_list.md
- Schulung:
    - Präsentation: presentation.md
